#!/bin/sh

echo "Starting rcS..."
echo "++ Mounting filesystem"
mount -t tmpfs tmpfs /dev
mount -t proc none /proc
mount -t sysfs none /sys
echo "++ Create tty1,2,3,4"
mknod /dev/tty1 c 4 1
mknod /dev/tty2 c 4 2
mknod /dev/tty3 c 4 3
mknod /dev/tty4 c 4 4
echo "rcS Complete"
